# Generated by Django 4.1.7 on 2023-03-13 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.SmallIntegerField(verbose_name='Créditos')),
                ('semestre', models.CharField(choices=[('', '-------------'), ('1', '1er. Semestre'), ('2', '2do. Semestre'), ('3', '3er. Semestre'), ('4', '4to. Semestre'), ('5', '5to. Semestre'), ('6', '6to. Semestre'), ('7', '7mo. Semestre'), ('8', '8vo. Semestre'), ('9', '9no. Semestre')], max_length=2)),
                ('optativa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MateriasPrecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_actual', to='materias.materia', verbose_name='Materia')),
                ('materia_precedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_precedente', to='materias.materia', verbose_name='Materia precedente')),
            ],
        ),
    ]
