# Generated by Django 4.1.6 on 2023-04-26 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='avatar',
            field=models.ImageField(upload_to='perfiles', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'], message='Sólo se permiten imágenes PNG')], verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='matricula_invalida', message='La matricula no tiene un formato válido', regex='^\\d{8}$')], verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='matricula',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='matricula_invalida', message='La matricula no tiene un formato válido', regex='^\\d{8}$')], verbose_name='Matrícula'),
        ),
    ]
