# Generated by Django 4.1.7 on 2023-03-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('matricula', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Matricula')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
            ],
        ),
    ]
