# Generated by Django 4.1.7 on 2023-03-27 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_estado_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='docentes.estado', verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='docentes.municipio', verbose_name='Municipio'),
            preserve_default=False,
        ),
    ]
