# Generated by Django 4.1.7 on 2023-03-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0003_docente_estado_docente_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='nombre',
            field=models.CharField(default=1, max_length=150, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
